name: Build and Package
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake dpkg-dev rpm
        
    - name: Configure and Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        
    - name: Create Packages
      run: |
        cd build
        cpack -G TGZ
        cpack -G DEB
        cpack -G RPM
