name: Build and Package
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake dpkg-dev rpm
        
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install wixtoolset -y
        echo "WIX=C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_ENV
    - name: Prepare license
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        if (!(Test-Path "LICENSE.rtf")) {
            " " | Out-File -Encoding ASCII "LICENSE.rtf"
        }
      
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install cmake
        
    - name: Configure and Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Create Packages (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        cpack -G TGZ
        cpack -G DEB
        cpack -G RPM
        
    - name: Create Packages (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        cpack -G WIX -C Release -V --debug
        
    - name: Create Packages (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd build
        cpack -G DragNDrop
